name = "multi-torrent-spoofer"
main = "src/index.js"
compatibility_date = "2024-03-04"
compatibility_flags = ["nodejs_compat"]

# Secrets (To set these, use `npx wrangler secret put BOT_TOKEN`)
# [vars]
# BOT_TOKEN = "your_bot_token"

[[kv_namespaces]]
binding = "TORRENTS_KV"
id = "your_kv_namespace_id_here"

[triggers]
crons = ["* * * * *"]
